### ISSUE TITLE
This is awesome! Love to see that your updating it! Having a little trouble installing, any help?

### ISSUE THREAD

**Issue by AshVan1** [JacobJustice/SneakerPricePrediction#1]
This is so cool! Love to see that your updating it! Having some trouble installing, any help?

**Comment by JacobJustice** [comment]
I'm happy to help, I'm not done with the project yet so I haven't gotten around to writing any install/use instructions sorry, the webscraper is for the most part complete.

If you're interested in any aspects of the project please let me know.

**Comment by AshVan1** [comment]
Ya that's cool just want a good prediction tool! Let me know when it's
finished!!
